Feature/dmp 641 Market on google maps
DeAceroDLabs/marketplace-frontend pull request #107
Opened 2022-10-24 23:06 UTC by dianabasilio

## What is done

[[DMP-641] Market on google maps](https://deacero.atlassian.net/browse/DMP-641)

## How is done

- Added functionality so that  map location changes depending on postal code.
- Added Marker to maps.
![image](https://user-images.githubusercontent.com/81311646/197646312-ef6b9e1f-0ec3-4a34-aa23-5d4ad75b87dc.png)

- Zoom updates.

## How to test

1. Run the project via `npm start`
2. Go to registrarse.
3. Fill first form.
4. On the second form map should be displayed and you should be able to see and change the marker with no problems.

2022-10-25 22:21 UTC, markriverac requested changes

2022-10-25 22:21 UTC, markriverac commented on src/config/api/api.ts
> +  return fetchData(`https://maps.googleapis.com/maps/api/geocode/json?skip_auth&components=postal_code:${postalCode}|country:${country}&region=AU&key=${apiKey}`);
This api route should be defined just as the other routes we use. In the api.types file

2022-10-25 22:21 UTC, markriverac commented on src/components/common/Map/Map.tsx
> +        <MarkerF position={centered} />
why the rename or what F means?

2022-10-25 23:22 UTC, dianabasilio commented on src/components/common/Map/Map.tsx
> +        <MarkerF position={centered} />
turns out Marker does not work anymore on recent react versions, the correct name now for this is MarkerF.

2022-10-26 19:04 UTC, markriverac requested changes

2022-10-26 19:04 UTC, markriverac commented on src/config/api/api.ts
> +  return fetchData(`https://maps.googleapis.com/maps/api/geocode/json?skip_auth&components=postal_code:${postalCode}|country:${country}&region=AU&key=${apiKey}`);
@dianabasilio what I meant with my comment is that we shouldn't do a `fetchData("maps.googleapis...");`
We should do a `fetchData(API.mapsAPI(postalCode, country, apiKey)``
Also, I think the apiKey should be somewhere defined, and not to be called as a param

2022-10-26 21:04 UTC, markriverac approved these changes

2022-10-26 21:04 UTC, markriverac commented on src/components/Form/MapField/MapField.tsx
> +      getLatLngFromPostalCode(parseInt(zipCode), "MX").then((data) => {
Nice! My comment didn't cover this change, thank you!

2022-10-26 21:04 UTC, markriverac commented on src/config/api/api.ts
> +  return fetchData(API.mapsAPI(postalCode, country));
😮‍💨

2022-10-26 21:31 UTC, merged