Feature/dmp 666
DeAceroDLabs/marketplace-frontend pull request #117
Opened 2022-11-03 15:17 UTC by dianabasilio

## What is done

[[DMP-666] Notification component](https://deacero.atlassian.net/browse/DMP-666)

## How is done

- Created a `Notification` component that will be used when user click on Agregar al carrito.
- Created a `notificationOpenContext` so that we can open or close notification throughout all the routes.

## How to test

1. Run the project via `npm start`
2. Click on any product.
3. Click `Agregar al carrito` button.
4. This button should navigate to home with and show a notification.
5. You should see be able to close the notification with the close button on the top right.
6. You should be able to close notification by clicking outside of it.

2022-11-03 22:52 UTC, markriverac requested changes

2022-11-03 22:52 UTC, markriverac commented on src/components/common/Notification/Notification.tsx
> +  children: React.ReactNode;
I think we shouldn't send a children to the Notification component.
Instead, the Notification itself should talk to the Notification Provider and get the last notification sent.

2022-11-03 22:52 UTC, markriverac commented on src/components/common/Notification/Notification.tsx
> +    <div
This component should have styles that make the component appear above everything. With this, the component should exist inside the App component and listen to the ContextProvider so when a notification is sent, this component should appear

2022-11-03 22:52 UTC, markriverac commented on src/config/notificationOpenContext.tsx
> +  notificationOpen: boolean;
I recommend that instead of setting true or false for getting the notification open, you send the data that the notification will have so the Notification component hear for this info and make itself visible

2022-11-03 22:52 UTC, markriverac commented on src/views/Home/Home.tsx
> +  const { notificationOpen } = useContext(NotificationOpenContext);
We shouldn't be calling for a notification inside of a single view, because then it would mean that the notification will only exist in this component. For this particular case it works, but maybe later we don't move the user to the home page when a notification is created.

2022-11-03 22:52 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    setNotificationOpen(true);
Here we should be sending the data of the product we want to push

2022-11-03 22:54 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    setNotificationOpen(true);
I will solve this on the next pr.

2022-11-04 16:36 UTC, dianabasilio commented on src/components/common/Notification/Notification.tsx
> +    <div
Okey I already added this, but for this specific notification we need this behavior:
https://deacerolabs.slack.com/files/U01D06DCJSF/F048ZUT0H7V/mercado_libre_m__xico_-_env__os_gratis_en_el_d__a_-_google_chrome_2022-11-01_09-29-58.mp4

2022-11-04 16:39 UTC, dianabasilio commented on src/config/notificationOpenContext.tsx
> +  notificationOpen: boolean;
Done

2022-11-04 16:40 UTC, dianabasilio commented on src/views/Home/Home.tsx
> +  const { notificationOpen } = useContext(NotificationOpenContext);
I am not sure if I solved this in specific.. but let me know

2022-11-04 17:07 UTC, markriverac requested changes

2022-11-04 17:07 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    setNotificationData(notificationContent);
I think you can pass the component directly, isn't it? `setNotificationData(<NotificationContent />)`, I would rename both to `setNotification(<NewProductAddedNotification />)`

2022-11-04 17:07 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +  const openNotification = () => {
I'd change the name of this function to `addNewProduct()` or `addProductToCart()` as you are not only opening the notification but the main thing you're doing is adding a new product to the shopping cart

2022-11-04 17:07 UTC, markriverac commented on src/views/Home/Home.tsx
> +import Notification from "components/common/Notification";
The Notification component should live in the App component, so every component has access to it. In this case, you will only see the Notification on the home screen. But if we add new variants later, we shouldn't be creating a notification on every component we want to see it.

2022-11-04 17:07 UTC, markriverac commented on src/components/common/Notification/Notification.tsx
> +import { useRef, useContext } from "react";
This component is almost ready to go. This component should live in the App component. And the styles you are adding to the notification container in the Home component should be (if necessary) in this component. The Notification should be independent of other components, except for the App which will live on and the Notification context which allows the notification to be visible

2022-11-07 16:58 UTC, markriverac approved these changes
👍🏼

2022-11-07 17:28 UTC, merged