[DMP-685] Reduced card size
DeAceroDLabs/marketplace-frontend pull request #120
Opened 2022-11-04 13:16 UTC by luisdeacero

## What is done

[[DMP-685] Corregir tamaño cards](https://deacero.atlassian.net/browse/DMP-685)

## How is done

1. Changed min-width for medium sized cards

## How to test

1. Run the project via `npm start`
3. On home, check cards don't overflow over to the right
## Evidence

BEFORE
![image](https://user-images.githubusercontent.com/116199447/199981596-5a71eb5f-1277-4896-86d4-95b184894989.png)

AFTER
![image](https://user-images.githubusercontent.com/116199447/199981238-118a52ca-5ccb-4ecb-9fcd-cea8376fe06b.png)

2022-11-04 16:42 UTC, dianabasilio requested changes

2022-11-04 16:42 UTC, dianabasilio commented on src/components/common/ImageCard/ImageCard.module.scss
> +    min-width: 272px;
![image](https://user-images.githubusercontent.com/81311646/200029585-4884b3de-9e21-4806-89dc-90e59aa65478.png)
I think it should be smaller, also the height. Thank you!

2022-11-04 16:44 UTC, dianabasilio commented on src/components/common/ImageCard/ImageCard.module.scss
> +    min-width: 272px;
Alse you can use media queries, so that this card size changes when window is smaller than 1300 and please make sure only these cards are affected and not these ones:
![image](https://user-images.githubusercontent.com/81311646/200030035-ced8180d-1840-482d-a817-0d26a136f3c1.png)

2022-11-08 19:50 UTC, dianabasilio commented
Hi Luis. in the past we changed the card height because they looked crushed, but then the problem was that the 4 rows did not fit on smaller screens. I think the we have the initial problem again.
the images look crushed again:

![image](https://user-images.githubusercontent.com/81311646/200660743-89d87d12-27f5-40be-b76f-4d6539565f0e.png)

2022-11-08 20:26 UTC, dianabasilio requested changes

2022-11-08 20:26 UTC, dianabasilio commented on src/views/Home/Home.tsx
> +            size="small"
We decided to use medium because small cards look weird on the images we have right now.

2022-11-08 20:26 UTC, dianabasilio commented on src/views/Home/Home.tsx
> +            size="small"
You can edit the first useEffect of this file to be like this:
```
  useEffect(() => {
    setmaxElementsToShow(4);
    if (largeScreen) {
      setmaxElementsToShow(5);
      setCardsPerRow(4);
    } else {
      setCardsPerRow(3);
    }
    mediumScreen && setmaxElementsToShow(2);
    smallScreen && setmaxElementsToShow(1);
  }, [largeScreen, mediumScreen, smallScreen]);
```

2022-11-09 17:45 UTC, dianabasilio requested changes

2022-11-09 17:45 UTC, dianabasilio commented on src/views/Home/Home.tsx
> +      <LoadingCard cards={CardsPerRow * 2} variant="small" />
Just one small change, please change this variant to medium 💯

2022-11-09 18:31 UTC, markriverac requested changes
Works great!
Just make the change Diana suggested about the cards and it will be approved

2022-11-09 21:15 UTC, dianabasilio approved these changes

2022-11-09 21:17 UTC, merged