Feature/dmp 687
DeAceroDLabs/marketplace-frontend pull request #126
Opened 2022-11-09 17:35 UTC by dianabasilio

## What is done

[[DMP-687] click on little carousel images](https://deacero.atlassian.net/browse/DMP-687)

## How is done

- Changed type CartProduct so that it receives sku, quantity, userId, articleId too.
- Passed selectedProperties to characteristics,
- Passed price with value 1 for now, later I will delete it.

## How to test

Clear local storage:
![image](https://user-images.githubusercontent.com/81311646/200900756-33934b07-cb6f-4555-91b1-5101a5cd0759.png)

1. Run the project via `npm start`.
2. Click on any product.
3. Click `Agregar al carrito` button.
4. Click `Ver carrito` button. You should see the product you just added.

.

2022-11-10 22:18 UTC, markriverac requested changes

2022-11-10 22:18 UTC, markriverac commented on src/components/common/common.types.ts
> +  images: { image_id: number; url: string }[];
I think we should keep using string as a type for this prop. We don't need the entire array of images, we can just send the first image that has no problem.

2022-11-10 22:18 UTC, markriverac commented on src/components/common/common.types.ts
> +  articleId: 0;
Why 0 and not number?

2022-11-10 22:18 UTC, markriverac commented on src/components/common/common.types.ts
> +  sku: number;
I think this is actually a string

2022-11-10 22:18 UTC, markriverac commented on src/components/common/common.types.ts
> +  characteristics: { prop: string; value: string; id: number }[];
In `ProductDetailView` there is a type for this, we should declare it here and use it in both files

2022-11-10 22:18 UTC, markriverac commented on src/views/Home/Home.tsx
>  import SearchBar from "components/common/SearchBar";
I think we don't need the shopping cart items in the home view, only on the Header, maybe?

2022-11-10 22:18 UTC, markriverac commented on src/views/ProductDetailView/NewProductAddedNotification/NewProductAddedNotification.tsx
> +          src={shoppingCartItems[indexLastCartItem].images[0].url}
Now I know that the best way of getting the last item of an array is to use slice.
```javascript
const lastItemInCartImg = shoppingCartItems.slice(-1).imgSrc // this way if we just add an image instead of an array of images to the cart item
src={lastItemInCartImg}

```

2022-11-10 22:18 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +  const { setValue } = useLocalStorage("cartItems", []);
Here you are setting an array as default, but as in App file you defined it as an empty object, then this is omitted. Just if you remove the localstorage and access to this it would work

2022-11-10 22:18 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    if (product.groupedProduct.productName) {
let's use productId instead of productName as we know that that param will always have a value, but not necessarily a name

2022-11-10 22:18 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +                    disable={activeSku === "No existe el producto" && true}
this should check on the price instead of the sku

2022-11-10 22:18 UTC, markriverac commented on src/views/ShoppingCart/ShoppingCartItem/ShoppingCartItem.tsx
> +    item.characteristics &&
I believe you don't need need to add this validation as `productDetailsKeys ` already did it before

2022-11-10 23:25 UTC, dianabasilio commented on src/components/common/common.types.ts
> +  articleId: 0;
It was not available before but I already added it

2022-11-10 23:44 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +                    disable={activeSku === "No existe el producto" && true}
Done

2022-11-11 16:38 UTC, markriverac requested changes
I just thought of this, it should have been resolved in the PR prior to this, but we can solve it here. 
When we add a product to the cart, we should check if the SKU or productID already exists in it, and instead of adding the full item, we should just increase the quantity of the product.

If we don't do that we could end up with 20 identical cards instead of one that indicates that there are 20 of these. Also, it could cause a problem when requesting offers.

<img width="829" alt="Screen Shot 2022-11-11 at 10 35 42" src="https://user-images.githubusercontent.com/68872548/201387102-d42cf13e-1d39-410a-89e7-e28c286bc0e9.png">

2022-11-11 16:38 UTC, markriverac commented on src/components/common/common.types.ts
> +  characteristics: { prop: string; value: string; id: number }[];
we still need to address this @dianabasilio

2022-11-11 16:38 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      setValue(currentItems);
we also need to send the request to the cart items service to post the item. The payload should be as follows:
```script
POST localhost:3000/cart-items
{ 
  "quantity": quantity, 
  "sku": id, 
  "userId": userId 
}
```
and everything else (setShoppingCartItems(currentItems) and setValue(currentItems))should be done only if the request to the cart-items service returns a success. So it would look like this:
```javascript
const itemToPush = {sku: id, userId: userId, quantity: quantity}
publishCartItem(itemToPush).then(() => {
     setShoppingCartItems(currentItems);
     setValue(currentItems);
});
```
If we add items to the local storage, but these aren't sent to the shoppingCart table, then we would not get any offers as there will not be any items in the cart.

2022-11-11 21:00 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      setValue(currentItems);
I already added the quantity update if repeated sku, and I thought this would be done on this jira: https://deacero.atlassian.net/jira/software/projects/DMP/boards/214/backlog?selectedIssue=DMP-690

But no probs ;)

2022-11-15 15:50 UTC, markriverac requested changes

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      sku: Number(activeArticle.sku),
here we need to send the articleId instead of the SKU: `SKU: activeArticle.articleId`

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    const productAlreadyOnCart = shoppingCartItems.find((item, i) => {
using a name like this makes me think that you are only searching for the product, but if I come to the code, I see that you are doing much more than just checking if the product was already on the cart list.

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +        shoppingCartItems[i].quantity =
Why do you need to do all this rounding for updating quantity if this is supposed to always be an integer number? 🤔

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +          shoppingCartItems.splice(shoppingCartItems.indexOf(item), 1)[0]
You actually already have the index, `i` should be the index of `item`? so you could just do `shoppingCartItems.splice(i, 1)[0]`

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      productAlreadyOnCart === undefined
this should be `product.groupedProduct.productId &&
      !productAlreadyOnCart`

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +        return false;
you don't need the `else` statement:
```javascript
...
    return true;
  }
  return false;
}
```

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      productAlreadyOnCart === undefined
Actually, `productAlreadyOnCart` I don´t think you need the `productAlreadyOnCart` validation because you are updating the shoppingCartItems in the find method. I think all those updates should be done after you validated that the product already exists in the shopping cart.

```javascript
if (item.sku === activeArticle.sku) {
        shoppingCartItems[i].quantity =
          Math.ceil(
            Math.round((shoppingCartItems[i].quantity + quantity) * 100 * 1e9) /
              1e9
          ) / 100;
        shoppingCartItems.push(
          shoppingCartItems.splice(shoppingCartItems.indexOf(item), 1)[0]
        );
        currentCartItems = shoppingCartItems;
        return true;
      } else {
        return false;
      }
```
should be split into two functions:

``` javascript
const productAlreadyOnCart = shoppingCartItems.find((item) => {
  if (item.sku === activeArticle.sku) {
    return true;
  }
  return false;
}
```

``` javascript
const updatedProductsInCart = shoppingCartItems.map((item) => {
  if (item.sku === activeArticle.sku) {
    item.quantity = item.quantity + quantity
  }
  return item
}
setShoppingCartItems(updatedProductsInCart)
```

2022-11-15 15:50 UTC, markriverac commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    }
I think we can update this function to something more clear. I am not sure if this code works, but it would be something like it:
```javascript
    const productAlreadyOnCart = shoppingCartItems.find((item) => {
      if (item.sku === activeArticle.sku) {
        return true;
      }
      return false;
    });

    if (product.groupedProduct.productId) {
      if (productAlreadyOnCart) {
        currentCartItems = shoppingCartItems.map((item) => {
          if (item.sku === activeArticle.sku) {
            item.quantity = item.quantity + quantity;
          }
          return item;
        });
      } else {
        const currentItems = [
          ...shoppingCartItems,
          {
            id: Number(activeArticle.articleId),
            title: product.groupedProduct.productName,
            sku: activeArticle.sku,
            quantity: quantity,
            userId: userData.id,
            articleId: Number(activeArticle.articleId),
            price: price,
            srcImage: product.groupedProduct.images[0].url,
            characteristics: selectedProperties,
          } as CartProduct,
        ];
        currentCartItems = currentItems;
      }
    }
```

2022-11-15 16:03 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +          shoppingCartItems.splice(shoppingCartItems.indexOf(item), 1)[0]
It has to be at the end, because the notification component only gets the last one.

2022-11-15 16:05 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      sku: Number(activeArticle.sku),
isn´t sku different from articleId?
```
id: number;
  sku: string;
  quantity: number;
  userId: number;
  articleId: number;
  title: string;
  price: number;
  srcImage: string;
  characteristics: { prop: string; value: string; id: number }[];
```

2022-11-15 16:08 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +    const productAlreadyOnCart = shoppingCartItems.find((item, i) => {
The main purpose of that variable is to mark undefined if the item was not on the cart already.

2022-11-15 16:09 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +        return false;
The build marked warning if not yesterday, but I can try it now

2022-11-15 16:10 UTC, dianabasilio commented on src/views/ProductDetailView/ProductDetailView.tsx
> +      productAlreadyOnCart === undefined
ok

2022-11-15 17:30 UTC, markriverac approved these changes

2022-11-15 17:33 UTC, merged