[DMP-652] Added loading state to DetailProductView
DeAceroDLabs/marketplace-frontend pull request #141
Opened 2022-12-02 01:02 UTC by luisdeacero

## What is done

[[DMP-652] [Frontend] Agregar estado de loading en Detalle de producto](https://deacero.atlassian.net/browse/DMP-652)

## How is done

1. If product.groupedProduct has a value
2. Show the page as normal
3. If product.groupedProduct has no value
4. Show an html with divs and p with styles added to mock an empty page

## How to test

1. Run the project via `npm start`
2. Choose a product
3. You can view the page before it recieves a response with products info
4. Or go to ProductDetailView.tsx on line 269 and change product.groupedProduct to false
5. And you can view the loading state of the page indefinetly

## Evidence

Add images or screen  recordings on how the feature was working after and before the fix (if applies)

2022-12-12 22:50 UTC, markriverac requested changes
Thank you a lot for the refactoring. Just some small changes ;)

2022-12-12 22:50 UTC, markriverac commented on src/views/ProductDetailView/LoadingProduct/LoadingProduct.tsx
> +                ></p>
You could use a loop to render these as they are the same, so we avoid code duplication

2022-12-12 22:50 UTC, markriverac commented on src/views/ProductDetailView/LoadingProduct/LoadingProduct.tsx
> +              ></p>
Same here, try to avoid code duplication

2022-12-13 06:31 UTC, luisdeacero commented on src/views/ProductDetailView/LoadingProduct/LoadingProduct.tsx
> +              ></p>
Done

2022-12-13 06:48 UTC, luisdeacero commented on src/views/ProductDetailView/LoadingProduct/LoadingProduct.tsx
> +                ></p>
They are not duplicates on the last assigned className, but I could use a numeric value on styles to force a loop. Should I go with something like that or leave it as it is?

2022-12-13 20:14 UTC, markriverac commented on src/views/ProductDetailView/LoadingProduct/LoadingProduct.tsx
> +                ></p>
Oh, I didn't catch that. Okay, I'll approve

2022-12-13 23:53 UTC, merged