Feature/dmp 728
DeAceroDLabs/marketplace-frontend pull request #145
Opened 2022-12-15 21:01 UTC by dianabasilio

## What is done

[[DMP-728] show offers on payment](https://deacero.atlassian.net/browse/DMP-728)

## How is done

- Added mock Offers data to payment view.
- Created selectedOffer type, this will be used on the context that we will create later.

## How to test

1. Run the project via `npm start`.
2. Click on any product.
3. Click `Agregar al carrito` button.
4. Go to `carrito` then to payment.
5.  On payment file line 50 you can change the offer type to, Express, Estándar or  Similares depending wich you want to see: 
![image](https://user-images.githubusercontent.com/81311646/207966264-e50bad9a-2c8f-4c62-b592-0fffe868c164.png)

2022-12-15 22:48 UTC, markriverac requested changes
Just some small changes. 
And please remove the commits that don't belong here.

2022-12-15 22:48 UTC, markriverac commented on src/config/api/offers.types.ts
> +  delivery_options: { delivery_days: string; articles: any }[];
I think this prop should be an array of Shipments. You can find the info you need in there

2022-12-15 22:48 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +  console.log(selectedOfferData);
can you remove these

2022-12-16 19:55 UTC, dianabasilio commented on src/config/api/offers.types.ts
> +  delivery_options: { delivery_days: string; articles: any }[];
I decided to use Offer type, later with the real data I´ll be adding more adjusments to this.

2022-12-16 20:00 UTC, markriverac approved these changes
Yes. It's better this way so the adaptation will be easier. Thank you! <3

2022-12-16 21:03 UTC, merged