Feature/dmp 738 Real data offers payment
DeAceroDLabs/marketplace-frontend pull request #152
Opened 2022-12-27 23:00 UTC by dianabasilio

## What is done

[[DMP-738]  Real data offers payment](https://deacero.atlassian.net/browse/DMP-738)

## How is done

- Added test for offers
- Added vertical type to `Divider` component.

## How to test

1. Run the project via `npm start`.
2. Click on any product.
3. Click `Agregar al carrito` button.
4. Select an offer.
5. Go to payment view. You should see the real offer data on step 2.

.

2022-12-28 18:39 UTC, markriverac requested changes
There is something wrong with the styles of the delete button that need to be fixed:

https://user-images.githubusercontent.com/68872548/209857538-88bab55d-1720-4532-9e81-daf5fca91990.mov

But also, I suggest skipping the delete actions for now. This is because we need to update the offer, not the shopping cart. The last one needs to keep their products until the order is created so the user won't have to select the items again if they make a mistake before creating the order.
But also, for creating an order the backend service is expecting an offer, but we haven't tested it yet, so we don't know if deleting an item directly from the offer would make a difference.

2022-12-28 18:39 UTC, markriverac commented on src/config/api/api.types.ts
> +
All this was moved to inventory.api.types

2022-12-28 18:39 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +    if (selectedOffer.title === "Express") {
you don't need these validations. Just set the offer title to the one from the offer, and use the dictionary to set the description. Check how it was done in the OrderOptions component
![code](https://user-images.githubusercontent.com/68872548/209856960-100e9172-3a9f-4b8e-a5db-f5506ba67d88.png)

2022-12-28 18:39 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +                {offerArticles.map((item: ArticleDetail) => {
In my newest PR I added more data to the `selectedOfferArticles` so all the data you would need is available in the selectedOfferContext and you don't have to do this anymore

2022-12-28 18:39 UTC, markriverac commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +  const { setValue } = useLocalStorage("cartItems", []);
instead of removing items from the shoppingCart, try to use the data from the selectedOfferContext. We don't want to remove items from the shoppingCart until the order is created so the user can go to offers and select a different one if they want

2022-12-28 21:30 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +  const { setValue } = useLocalStorage("cartItems", []);
> There is something wrong with the styles of the delete button that need to be fixed:
> 
>  Screen.Recording.2022-12-28.at.12.21.24.mov 
> But also, I suggest skipping the delete actions for now. This is because we need to update the offer, not the shopping cart. The last one needs to keep their products until the order is created so the user won't have to select the items again if they make a mistake before creating the order. But also, for creating an order the backend service is expecting an offer, but we haven't tested it yet, so we don't know if deleting an item directly from the offer would make a difference.

I was talking with abe that maybe it would look better like this:
![image](https://user-images.githubusercontent.com/81311646/209874071-b264ff15-c031-473b-acc2-7245d7a73dbb.png)

2022-12-28 21:32 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +  const { setValue } = useLocalStorage("cartItems", []);
![image](https://user-images.githubusercontent.com/81311646/209874333-0623d45f-5d09-43a1-a7f7-77e6c383ac5b.png)

2022-12-28 21:39 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +  const { setValue } = useLocalStorage("cartItems", []);
void 0 for now when deleting article

2022-12-28 21:41 UTC, dianabasilio commented on src/views/Payment/Payment.tsx
> +                {offerArticles.map((item: ArticleDetail) => {
I will change this when you merge it to development.

2022-12-28 21:42 UTC, dianabasilio commented
![image](https://user-images.githubusercontent.com/81311646/209875220-0b62f3bf-1071-4abb-a1b5-e294503d9e3e.png)
Abe approved this design

2022-12-29 17:25 UTC, markriverac approved these changes
Just a small comment. :)

2022-12-29 17:25 UTC, markriverac commented on src/config/api/offers.types.ts
> -  //To do: when displaying real data change this to type ShipmentArticle[];
Remove this comment, please

2023-01-02 17:02 UTC, merged