[DMP-753] Add motive for purchase textarea on checkout
DeAceroDLabs/marketplace-frontend pull request #158
Opened 2023-01-07 00:19 UTC by luisdeacero

## What is done

[[DMP-753] [Frontend] Campo de motivo de compra](https://deacero.atlassian.net/browse/DMP-753)

## How is done

1. Added a variable with the html structure
2. Added the variable to the main structure
3. _Pending:_ Add the input to the api call

## How to test

1. Run the project via `npm start`
2. Add at least one product to your cart
3. Go through the payment process until the last page, and view the field as the third step

## Evidence

2023-01-09 17:49 UTC, markriverac requested changes

2023-01-09 17:49 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +      {userData.locationData && (
Why do you verify if the user has locationData for this?

2023-01-09 17:49 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +          ></textarea>
This should be a new component, part of the other fields' components. Just in case we want to add a textarea in a form later

2023-01-11 20:35 UTC, luisdeacero commented on src/views/Payment/Payment.tsx
> +          ></textarea>
Done. I hope I didn't miss anything.

2023-01-13 19:02 UTC, markriverac approved these changes
Just a small fix.
Other than that, it's all good (we will have to try it once the orders and openpay process is ready). Also, the merge will have to be done on your local machine :)

2023-01-16 19:05 UTC, merged