Feature/dmp 445
DeAceroDLabs/marketplace-frontend pull request #39
Opened 2022-07-01 21:12 UTC by dianabasilio

## What is done

[[DMP-445] Email  validation](https://deacero.atlassian.net/browse/DMP-445)

## How is done

- Added validateEmail and  validateDeAceroEmail funtions to `TextField` component that will validate deacero email and additional email.

## How to test

1. Run the project via `npm start`
2. npm i
3. Login
4. Go to /signup.
5. Test deacero email and additional email.

2022-07-01 22:30 UTC, markriverac requested changes

2022-07-01 22:30 UTC, markriverac commented on src/components/Form/TextField/TextField.tsx
>  import { useState } from "react";
I suggest creating a new component `EmailField` to separate this from the TextField and adding a prop `validateDomain` which allows us to validate that the email is from a specific domain, in this case, we pass "deacero.com" but we could use it for other domains as well.

2022-07-04 17:17 UTC, markriverac requested changes

2022-07-04 17:17 UTC, markriverac commented on src/forms/form.types.ts
> +  validateDomain?: boolean;
instead of being `boolean`, this could be a string, so you can pass any domain

2022-07-04 17:17 UTC, markriverac commented on src/components/Form/EmailField/EmailField.tsx
> +    const isDeAceroEmail = email.split("@")[1] === "deacero.com";
using `validateDomain` as a string, you could do 
```javascript
const isValidDomain = email.split("@")[1] === validateDomain;
````

2022-07-04 17:17 UTC, markriverac commented on src/components/Form/EmailField/EmailField.tsx
> +    isDeAceroEmail ? setError("") : setError("Favor de ingresar un correo de DEACERO");
You could also pass a custom message as a prop so we don't use this validation only for DeAcero emails

2022-07-04 17:51 UTC, markriverac requested changes

2022-07-04 17:51 UTC, markriverac commented on src/forms/form.types.ts
> +  message?: string;
`errorMessage` would be more intuitive

2022-07-04 17:51 UTC, markriverac commented on src/components/Form/EmailField/EmailField.tsx
> +  const validateDeAceroEmail = (e: React.ChangeEvent<HTMLInputElement>) => {
The name of the function should change to something more general as well

2022-07-04 17:52 UTC, dianabasilio commented on src/components/Form/EmailField/EmailField.tsx
> +  const validateDeAceroEmail = (e: React.ChangeEvent<HTMLInputElement>) => {
Truee

2022-07-04 22:29 UTC, markriverac approved these changes

2022-07-05 15:35 UTC, merged