Feature/dmp 453
DeAceroDLabs/marketplace-frontend pull request #54
Opened 2022-07-18 22:42 UTC by dianabasilio

## What is done

[[DMP-453] Frequently asked questions page](https://deacero.atlassian.net/browse/DMP-453)

## How is done

- Created a `ToogleCategories` component that is used on Frequently asked questions page, the content visibility is toogle when clicking the button.
- Created a `FrequentQuestions` component.

## How to test

1. Run the project via `npm start`.
2. /login.
3. Click on `Preguntas Frecuentes` .

2022-07-18 22:43 UTC, dianabasilio commented
I have doubts with the components names.

2022-07-19 17:02 UTC, markriverac requested changes

2022-07-19 17:02 UTC, markriverac commented on src/components/common/ToogleCategories/ToogleCategories.tsx
> +  content: string;
This could be changed for a children, so we can add any kind of content as content

2022-07-19 17:02 UTC, markriverac commented on src/views/FrequentQuestions/FrequentQuestions.tsx
> +      <ToogleCategories
for simulating dynamic data, I suggest creating a JSON file with the data and rendering it instead of creating static or hardcoded code for each entry.

2022-07-20 14:22 UTC, markriverac requested changes

2022-07-20 14:34 UTC, dianabasilio commented on src/views/FrequentQuestions/FrequentQuestions.tsx
> +import ToogleCategories from "components/common/ToogleCategories";
Forgot to push it 😢 .

2022-07-20 17:44 UTC, markriverac approved these changes

2022-07-20 18:01 UTC, merged