Feature/dmp 525 Check products (step 2)  on payment view.
DeAceroDLabs/marketplace-frontend pull request #78
Opened 2022-08-16 18:21 UTC by dianabasilio

## What is done

[[DMP-525] Check products on payment view](https://deacero.atlassian.net/browse/DMP-525)

## How is done

- Created a `PaymentItem` component that will be used to show all the items (products) on the Payment view.

## How to test

1. Run the project via `npm start`.
2. login.
3. Go to `carrito/pago`. You should see the Check products step.

2022-08-16 21:44 UTC, markriverac requested changes

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +        <div className={styles.subtitle}>2. Verifica tus artículos </div>
I feel like this could be a component like the `Section`, modifying it to add the "action" (button to add more items) or creating a new "PaymentSection".

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +      <div className={styles["check-container"]}>
This could be another component, similar to the Card component, maybe adding a variant without shadows or creating another more specific.

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +        <div className={styles["grey-box-info"]}>
This one also could be another component or a Section with a grey background

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +        <div className={styles["flex-space-between"]}>
This could be more like a Table component

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +          </div>
This would be the TableHeader

2022-08-16 21:44 UTC, markriverac commented on src/views/Payment/Payment.tsx
> +      </div>
This would be the TableBody, or Rows

2022-08-16 21:48 UTC, dianabasilio commented on src/components/common/Divider/Divider.tsx
> +    const marginClass = margin ? "" : "no-margin";
All of the divider components that we have right now in the application have a little margin that looks good, if default value is false, we have to change them all.

2022-08-16 21:49 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +        <Divider color="grey" margin={false} />
This extra line is in the design mockup.

2022-08-16 22:01 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +            <div className={styles.detail}>{productDetails}</div>
![image](https://user-images.githubusercontent.com/81311646/184992902-c48e82bd-786c-4a24-9641-0deeec432144.png)
I just ask the Ux team, if this looks good (the delete button always at the end).

2022-08-16 22:08 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +            <div className={styles.detail}>{productDetails}</div>
Ux team proposal:
![image](https://user-images.githubusercontent.com/81311646/184993820-1f999bae-bcc5-4f5e-a62a-42b33e1eafb8.png)

2022-08-16 22:11 UTC, dianabasilio commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +            <div className={styles.detail}>{productDetails}</div>
I will try to fix the margins/padding between multimalla and details also.

2022-08-16 22:47 UTC, markriverac commented on src/components/common/Divider/Divider.tsx
> +    const marginClass = margin ? "" : "no-margin";
Yup. I think we should do that. In a different PR though. Thank you!

2022-08-16 22:48 UTC, markriverac commented on src/views/Payment/PaymentItem/PaymentItem.tsx
> +        <Divider color="grey" margin={false} />
Oh! I think it looks strange. But okay!
Also, we need to consider when we have many items in the cart. Should this display a long list of items, or should we have a max-height property and display a scrollbar?

2022-08-16 23:41 UTC, dianabasilio commented on src/views/Payment/Payment.tsx
> +      </div>
I let this as child prop in `Table` component, but I´m not sure if it´s okay.

2022-08-17 19:06 UTC, markriverac requested changes

2022-08-17 19:06 UTC, markriverac commented on src/views/Payment/PaymentSection/PaymentSection.tsx
> +import styles from "./PaymentSection.module.scss";
instead of creating a new component, let's modify the existing one. We can add an extra prop "Action". I say so because this is pretty similar to a Section component but with less code

2022-08-17 19:06 UTC, markriverac commented on src/components/common/Table/Table.tsx
> +  primaryColumnName?: string;
we can remove the "Name" part of the name of the props. It's redundant

2022-08-17 21:32 UTC, markriverac approved these changes
🫶🏻

2022-08-17 21:50 UTC, merged