Feature/dmp 550  Carousel component
DeAceroDLabs/marketplace-frontend pull request #88
Opened 2022-09-02 01:29 UTC by dianabasilio

## What is done

[[DMP-550] Carousel component](https://deacero.atlassian.net/browse/DMP-550)

## How is done

- Created a `Carousel` component that will be used  to show all categorues on home page and to show the product images on ProductDetail view.
- This Carousel now receives two types: "images" and "tabs".
- Added `@react-hook/media-query` module to change number of visible elements inside carousel depending on window size.

## How to test

1. Run the project via `npm start`
2. npm i
3. You should see the Home Screen with categories carrousel. Play with it by clicking on categories and arrow buttons.
4. To view the `@react-hook/media-query` usage, please change the window size with development tools.
5. /producto/1
6. You should see the images carrousel.

2022-09-02 20:58 UTC, markriverac approved these changes

2022-09-02 20:58 UTC, markriverac commented on src/components/common/Carousel/Carousel.tsx
> +  const [lastIndex, setLastIndex] = useState(maxElementsToShow);
To avoid loading and handling multiple states, we could use a single state defining a type like: 
```javascript
interface CarouselState = {
  resultList: Array<Any>;
  largeImage: array[0];
  firstIndex: number;
  maxElementsToShow: number;
}
````
then, we can declare a single state like 
```javascript 
const [carouselState, setCarouselState] = useState({
    results: Array<any>,
    largeImage: array[0],
    firstIndex: 0, 
    lastIndex: maxElementsToShow
} as CarouselState);
```
and to modify any, let's say the `largeIamge`:

```javascript
setCarouselState( {...carouselState, largeImage: array[1])
```

2022-09-02 20:58 UTC, markriverac commented on src/components/common/Carousel/Carousel.tsx
> +  const [lastIndex, setLastIndex] = useState(maxElementsToShow);
This is just a reccomendation

2022-09-02 20:58 UTC, markriverac commented on src/components/common/Carousel/Carousel.tsx
> +      setFirstIndex(firstIndex + 1);
this can be rewritten in a function 

```javascript 
const moveIndex = (direction: 1 | -1)  => {
  setLastIndex(lastIndex + direction)
  setFirstIndex(firstIndex + 1);
}
```

2022-09-02 23:18 UTC, dianabasilio commented on src/components/common/Carousel/Carousel.tsx
> +  const [lastIndex, setLastIndex] = useState(maxElementsToShow);
I am not sure why, I tried using this kind of recommendation but only updates correctly the largeImage. I left a commit with those changes but I change it back to how it was later in another commit.

2022-09-05 14:27 UTC, markriverac requested changes
We need to work on the styles because for smaller windows, it shows overlapped.
![Screen Shot 2022-09-05 at 9 26 29](https://user-images.githubusercontent.com/68872548/188471417-eace8687-dc84-4c15-a30c-be5a3cddda3e.png)

2022-09-05 14:31 UTC, markriverac requested changes
I think, when we click on the "next" or "back" button, the main image should change. We shouldn't need to select the image we want to see. Maybe it is a question for UX

https://user-images.githubusercontent.com/68872548/188471936-6df78586-597b-46ba-b0ba-cda6056e9976.mov

2022-09-06 15:47 UTC, dianabasilio commented
> I think, when we click on the "next" or "back" button, the main image should change. We shouldn't need to select the image we want to see. Maybe it is a question for UX
> 
>  Screen.Recording.2022-09-05.at.9.28.17.mov

![image](https://user-images.githubusercontent.com/81311646/188679092-fcd499c6-879d-4396-a6d9-925f7a02a90d.png)
The UX team proposed to leave it as the way it is already.

2022-09-07 16:35 UTC, markriverac requested changes

2022-09-07 16:35 UTC, markriverac commented on src/views/Home/Home.tsx
> +    smallScreen &&  setmaxElementsToShow(1);
This could change to 
``` javascript
setmaxElementsToShow(4); // this would be the default value and in case of the condition is met, the value would change
largeScreen && setmaxElementsToShow(6);
mediumScreen &&  setmaxElementsToShow(2);
smallScreen &&  setmaxElementsToShow(1);
```

2022-09-07 16:35 UTC, markriverac commented on src/views/ProductDetail/ProductDetail.tsx
> +  console.log('smallScreen ',smallScreen);
remove these logs, please

2022-09-07 16:35 UTC, markriverac commented on src/views/ProductDetail/ProductDetail.tsx
> +    smallScreen && mediumScreen &&  setmaxElementsToShow(1);
this should be the same as in home
```javascript
largeScreen && setmaxElementsToShow(4);
mediumScreen && setmaxElementsToShow(3);
smallScreen && setmaxElementsToShow(1);
```

2022-09-07 16:36 UTC, markriverac commented on src/views/ProductDetail/ProductDetail.tsx
> +  console.log('smallScreen ',smallScreen);
nvm, I saw you did it on the last commit

2022-09-08 18:33 UTC, markriverac approved these changes

2022-09-08 19:02 UTC, markriverac requested changes

2022-09-08 19:02 UTC, markriverac commented on src/views/ProductDetail/__tests__/ProductDetail.test.tsx
> +          },
```javascript
Promise.resolve({
        data: productsDetailRespose,
      })
```

2022-09-08 19:02 UTC, markriverac commented on src/setupTests.ts
> +const getProductDetail = (productId: number): ProductDetail => {
```javascript
const getProductDetail = (): ProductDetail => {
```

2022-09-08 19:02 UTC, markriverac commented on src/setupTests.ts
> +export const productsDetailRespose: ProductDetail = getProductDetail(1234);
```javascript
export const productsDetailRespose: ProductDetail = getProductDetail();
```

2022-09-09 21:42 UTC, markriverac approved these changes

2022-09-12 17:43 UTC, merged